<?php

namespace Neton\FrameworkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AclRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclRepository extends EntityRepository
{
}
