<?php

namespace Neton\FrameworkBundle\Repository;

/**
 * BundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BundleRepository extends BaseRepository
{
    /**
     * @var string
     * Entidade de manipulação de bundles.
     */
    protected $entity = '\\Neton\\FrameworkBundle\\Entity\\Bundle';
    
    /**
     * Mapa de alias das entidades.
     * 
     * @var array 
     */
    protected $aliasMap = array(
        '' => 'b'
    );
    
    /**
     * Campos a serem utilizados na pesquisa básica.
     * 
     * @var arrau
     */
    protected $basicSearchFields = array(
       'b.name','b.title','b.iconCls'
    );
    
    /**
     * Retorna a lista dos bundles cadastrados no sistema.
     * 
     * @param array $params
     */
    public function getList($params)
    {
        $qb = $this->_em->createQueryBuilder()
                ->select('b')
                ->from($this->entity, 'b');
        
        // aplica os filtros à consulta
        $qb = $this->applyFilter($qb, $params);     
        
        // aplica a ordenação
        $qb = $this->applySort($qb, $params);
        
        // conta os registros encontrados
        $count = count($qb->getQuery()->getArrayResult());
        
        // aplica a paginação
        $qb = $this->applyPaging($qb, $params);
        
        // recupera os resultados
        $rs = $qb->getQuery()->getResult('FlatScalar');
        
        // retorna os resultados encontrados
        return array (
            'results' => $rs,
            'total' => $count
        );
    }
}
