<?php

namespace Neton\FrameworkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BundleRepository extends EntityRepository
{
    /**
     * @var string
     * Entidade de manipulação de bundles.
     */
    protected $entity = '\\Neton\\FrameworkBundle\\Entity\\Bundle';
    
    /**
     * Retorna a lista dos bundles cadastrados no sistema.
     * 
     * @param array $params
     */
    public function getList($params)
    {
        $qb = $this->_em->createQueryBuilder()
                ->select('b')
                ->from($this->entity, 'b')
                ->orderBy('b.orderIndex','ASC');
        
        $rs = $qb->getQuery()->getResult('FlatScalar');
        
        return $rs;
    }
}
