<?php

namespace Neton\FrameworkBundle\Repository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends BaseRepository
{
    /**
     * @var string
     * 
     * Nome da classe da entidade Module.
     */
    protected $entity = '\\Neton\\FrameworkBundle\\Entity\\Module';
    
	/**
	 * Mapa de alias de entidades.
	 * 
	 * @var array
	 */
	protected $aliasMap = array(
		'' => 'm',
		'bundle' => 'b'
	);
	
	/**
	 * Mapa de filtros básicos da consulta.
	 * 
	 * @var string
	 */
	protected $basicSearchFields = array(
		'm.name','m.title','m.title', 'b.title'
	);
	
    /**
     * Retorna a lista dos bundles cadastrados no sistema.
     * 
     * @param array $params
     */
    public function getList($params)
    {
        $qb = $this->_em->createQueryBuilder()
                ->select('m, b.id as bundle, b.title as bundle_name')
                ->from($this->entity, 'm')
                ->join('m.bundle','b');
        
		// aplica os filtros
		$qb = $this->applyFilter($qb, $params);
		
		// pega o total de resultados da consulta
		$count = count($qb->getQuery()->getArrayResult());
		
		// aplica a paginação
		$qb = $this->applyPaging($qb, $params);
		
		// aplica a ordenação
		$qb = $this->applySort($qb, $params);
		
		// pega o resultado da consulta
        $rs = $qb->getQuery()->getResult('FlatScalar');
        
		// retorna os resultados
        return array(
        	'results' => $rs,
        	'total' => $count        	
       	);
    }
    
    /**
     * Encontra e retorna os módulos para a exibição na inteface de usuário.
     * 
     * @param Integer $userId
     */
    public function findToUi($userId)
    {
        $qb = $this->_em->createQueryBuilder()
                ->select('m')
                ->from($this->entity, 'm')
                ->where('m.enabled = :enabled')
                ->setParameter('enabled','1');
        
        $bundles = array();
        
        $rs = $qb->getQuery()->getResult();
        
        foreach ($rs as $module){
            $bundle = $module->getBundle();
            
            // se o bundle estiver habilitado
            if ($bundle->getEnabled() == '1'){
                $bundleKey = 'b'.$bundle->getOrderIndex().'_'.$bundle->getName();

                if (!isset($bundles[$bundleKey])){

                    $bundles[$bundleKey] = array(
                        'name' => $bundle->getName(),
                        'title' => $bundle->getTitle(),
                        'iconCls' => $bundle->getIconCls(),
                        'isDefault' => (boolean) $bundle->getIsDefault(),
                        'modules' => array()
                    );
                }

                $moduleKey = 'm'.$module->getOrderIndex().'_'.$module->getName();

                $bundles[$bundleKey]['modules'][$moduleKey] = array(
                    'name' => $module->getName(),
                    'title' => $module->getTitle(),
                    'isDefault' => (boolean) $module->getIsDefault(),
                    'separator' => (boolean)$module->getSeparator(),
                    'iconCls' => $module->getIconCls()
                );
                
            }
        }
        
        // ordena os bundles de acordo com sua ordem
        ksort($bundles);
        
        // ordena os módulos de acordo com a ordem pré-definida
        foreach ($bundles as $name => $bundle){
            ksort($bundles[$name]['modules']);
        }
        
        
        return $bundles;

    }
}
